apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: logging-system
spec:
  releaseName: loki-stack
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki-repo
        namespace: flux-system
      version: 2.5.0
  values:
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h