image: python:3.11

variables:
  DB: "$DB_NAME"
  HOST: "$DB_HOST"
  LOGIN: "$DB_LOGIN"
  PASSWORD: "$DB_PASSWORD"

stages:
  - build
  - deploy

lint:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install flake8 mysqlclient
    - test -f requirements.txt && pip install -r requirements.txt
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

run_main:
  stage: build
  script:
    - python main.py

login_to_registry:
  image: docker:19.03.12
  stage: deploy
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build_and_push_docker:
  stage: deploy
  script:
    - docker build . -t "ghcr.io/$CI_REGISTRY_USER/base-pipeline:0.1"
    - docker push "ghcr.io/$CI_REGISTRY_USER/base-pipeline:0.1"