image: python:3.11

variables:
  DB: "$DB_NAME"
  HOST: "$DB_HOST"
  LOGIN: "$DB_LOGIN"
  PASSWORD: "$DB_PASSWORD"

cache:
  key:
    files:
      - requirements.txt
    prefix: ${CI_JOB_NAME}
  paths:
    - .venv
    - .cache/pip

stages:
  - build

install_requirements:
  stage: build
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

  script:
    - python -m pip install -r requirements.txt
    - python -m pip install mysqlclient

lint:
  stage: build
  script:
    - python -m pip install flake8
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

tests:
  stage: build
  script:
    - . .venv/bin/activate/ && python main.py

build_and_push_docker:
  variables:
    CI_VERSION: "1.0.${CI_JOB_ID}"
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "ghcr.io/$CI_REGISTRY_USER/base-pipeline:${CI_COMMIT_SHA:0:8}-$CI_PIPELINE_IID" .
    - docker push "ghcr.io/$CI_REGISTRY_USER/base-pipeline:${CI_COMMIT_SHA:0:8}-$CI_PIPELINE_IID"
