# HelmRepo находится в .loki/helmrelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.11"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: loki
  values:
    persistence:
      enabled: true
      size: 1Gi