---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: vlad.kanatik@ya.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notickets-ru
  namespace: default
spec:
  secretName: notickets-ru-tls
  duration: 90d
  renewBefore: 30d
  subject:
    organizations:
      - Lon8 Comp
  commonName: notickets.ru
  dnsNames:
    - notickets.ru
    - www.notickets.ru
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
