apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mysql-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://mysql.github.io/mysql-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-operator
spec:
  interval: 5m
  releaseName: mysql-operator
  chart:
    spec:
      chart: mysql-operator
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
      version: "2.1.3" # Убедитесь, что используете актуальную версию
  # Добавьте другие значения конфигурации по необходимости
