# mysql-operator/mysql-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-operator
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      containers:
      - name: mysql-operator
        image: mysql/mysql-operator:latest
        ports:
        - containerPort: 8443
