apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              members:
                type: integer
              rootPasswordSecret:
                type: object
              version:
                type: string
              volumeClaimTemplates:
                type: array
                items:
                  type: object
