apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/loki-stack
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: loki-stack
      namespace: logging-system
    spec:
      values:
        loki:
          persistence:
            enabled: true
            storageClassName: "gp2"
            size: 10Gi
        grafana:
          persistence:
            enabled: true
            storageClassName: "gp2"
            size: 1Gi