apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging-system
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.6.1"
      sourceRef:
        kind: HelmRepository
        name: loki
  values:
    persistence:
      enabled: true
      size: 10Gi