apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vector
  namespace: vector
spec:
  interval: 30m
  url: https://helm.vector.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 1m
  chart:
    spec:
      chart: vector
      version: "0.33.0"
      sourceRef:
        kind: HelmRepository
        name: vector
  values:
    customConfig:
      data_dir: "/vector-data-dir"

      sources:
        kubernetes_logs:
          type: kubernetes_logs
          glob_minimum_cooldown_ms: 1000
          ingestion_timestamp_field: ingestion_timestamp
      sinks:
        loki:
          type: loki
          inputs: ["sample"]
          endpoint: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
      tolerations:
        - key: service
          operator: Equal
          effect: NoSchedule
