apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vector
  namespace: vector
spec:
  interval: 30m
  url: https://helm.vector.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 1m
  chart:
    spec:
      chart: vector
      version: "0.33.0"
      sourceRef:
        kind: HelmRepository
        name: vector
  values:
    - values.yaml