apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.2"
      sourceRef:
        kind: HelmRepository
        name: loki
  values:
    loki:
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 30Gi
    grafana:
      enabled: false
    prometheus:
      enabled: false