name: Python application

on:
  push:
    branches: [ "pipeline", "pipeline_tags" ]
  pull_request:
    branches: [ "main" ]

env:
  DB: ${{ secrets.DB_NAME }}
  HOST: ${{ secrets.DB_HOST }}
  LOGIN: ${{ secrets.DB_LOGIN }}
  PASSWORD: ${{ secrets.DB_PASSWORD }}

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Cache Python dependencies
      uses: actions/cache@v2
      id: cache-python-deps
      with:
        path: .venv/
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      if: steps.cache-python-deps.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test main.py
      run: |
        source ./venv/bin/activate && python main.py
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository_owner }}/base-pipeline:${{ github.sha }}-${{ github.run_number }}
        docker push ghcr.io/${{ github.repository_owner }}/base-pipeline:${{ github.sha }}-${{ github.run_number }}