apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: logging-system
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.2"
      sourceRef:
        kind: HelmRepository
        name: loki-stack
  values:
    loki:
      persistence:
        enabled: true
        size: 10Gi
    grafana:
      enabled: true
      persistence:
        enabled: true
        size: 1Gi
    promtail:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: service
        operator: Equal
        effect: NoSchedule
      - key: app
        operator: Equal
        effect: NoSchedule